using System.Collections.Generic;

namespace PmxLib;

public class MaterialShaders
{
	public static List<MaterialShader> materialShaders = new List<MaterialShader>
	{
		new MaterialShader("Shader Forge/main_alpha", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineGA", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("outline", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("Koikano/main_clothes_alpha", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineGA", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("outline", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("xukmi/MainAlphaPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineGA", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("outline", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("xukmi/MainAlphaPlusTess", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineGA", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("outline", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("Shader Forge/main_emblem", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("shadowcolor", "Color"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("Koikano/main_clothes_emblem", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("shadowcolor", "Color"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("Shader Forge/main_emblem_clothes", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("alphamaskuv1", "Float")
		}),
		new MaterialShader("Shader Forge/main_hair", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("HairGloss", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("LineColor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float")
		}),
        new MaterialShader("Koikano/hair_main_sun", new List<MaterialShaderItem>
        {
            new MaterialShaderItem("AlphaMask", "Texture"),
            new MaterialShaderItem("AnotherRamp", "Texture"),
            new MaterialShaderItem("ColorMask", "Texture"),
            new MaterialShaderItem("DetailMask", "Texture"),
            new MaterialShaderItem("HairGloss", "Texture"),
            new MaterialShaderItem("MainTex", "Texture"),
            new MaterialShaderItem("NormalMap", "Texture"),
            new MaterialShaderItem("Color", "Color"),
            new MaterialShaderItem("Color2", "Color"),
            new MaterialShaderItem("Color3", "Color"),
            new MaterialShaderItem("LineColor", "Color"),
            new MaterialShaderItem("ShadowColor", "Color"),
            new MaterialShaderItem("rimpower", "Float"),
            new MaterialShaderItem("rimV", "Float"),
            new MaterialShaderItem("ShadowExtend", "Float"),
            new MaterialShaderItem("SpeclarHeight", "Float")
        }),
        new MaterialShader("xukmi/HairPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("HairGloss", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("LineColor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float")
		}),
		new MaterialShader("Shader Forge/main_hair_front", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("HairGloss", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("LineColor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float")
		}),
		new MaterialShader("Koikano/hair_main_sun_front", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("HairGloss", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("LineColor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float")
		}),
		new MaterialShader("xukmi/HairFrontPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("HairGloss", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("LineColor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float")
		}),
		new MaterialShader("Shader Forge/main_item", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("LineWidthS", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("Koikano/main_clothes_item", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("LineWidthS", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("xukmi/MainItemPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("LineWidthS", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("Shader Forge/main_item_ditherd", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("node_1554", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("shadowcolor", "Color"),
			new MaterialShaderItem("Cutoff", "Float")
		}),
		new MaterialShader("Shader Forge/main_item_emission", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnimationMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("EmissionPower", "Float"),
			new MaterialShaderItem("LineWidthS", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("UPanner", "Float"),
			new MaterialShaderItem("VPanner", "Float")
		}),
		new MaterialShader("Shader Forge/main_item_studio", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color1_2", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color2_2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color3_2", "Color"),
			new MaterialShaderItem("Patternuv1", "Color"),
			new MaterialShaderItem("Patternuv2", "Color"),
			new MaterialShaderItem("Patternuv3", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("OverColor3", "Color"),
			new MaterialShaderItem("Shadow", "Color"),
			new MaterialShaderItem("Spec", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("paint1", "Color"),
			new MaterialShaderItem("refcolor", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("ambientshadowOFF", "Float"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("EmissionPower", "Float"),
			new MaterialShaderItem("LineWidthS", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("patternclamp1", "Float"),
			new MaterialShaderItem("patternclamp2", "Float"),
			new MaterialShaderItem("patternclamp3", "Float"),
			new MaterialShaderItem("patternrotator1", "Float"),
			new MaterialShaderItem("patternrotator2", "Float"),
			new MaterialShaderItem("patternrotator3", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float")
		}),
		new MaterialShader("Shader Forge/main_item_studio_add", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("alpha", "Float")
		}),
		new MaterialShader("Shader Forge/main_item_studio_alpha", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color1_2", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color2_2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color3_2", "Color"),
			new MaterialShaderItem("Patternuv1", "Color"),
			new MaterialShaderItem("Patternuv2", "Color"),
			new MaterialShaderItem("Patternuv3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("EmissionPower", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("alpha", "Float"),
			new MaterialShaderItem("ambientshadowOFF", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("patternclamp1", "Float"),
			new MaterialShaderItem("patternclamp2", "Float"),
			new MaterialShaderItem("patternclamp3", "Float"),
			new MaterialShaderItem("patternrotator1", "Float"),
			new MaterialShaderItem("patternrotator2", "Float"),
			new MaterialShaderItem("patternrotator3", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("rimpower", "Float")
		}),
		new MaterialShader("xukmi/MainItemAlphaPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color1_2", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color2_2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color3_2", "Color"),
			new MaterialShaderItem("Patternuv1", "Color"),
			new MaterialShaderItem("Patternuv2", "Color"),
			new MaterialShaderItem("Patternuv3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("EmissionPower", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("alpha", "Float"),
			new MaterialShaderItem("ambientshadowOFF", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("patternclamp1", "Float"),
			new MaterialShaderItem("patternclamp2", "Float"),
			new MaterialShaderItem("patternclamp3", "Float"),
			new MaterialShaderItem("patternrotator1", "Float"),
			new MaterialShaderItem("patternrotator2", "Float"),
			new MaterialShaderItem("patternrotator3", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("rimpower", "Float")
		}),
		new MaterialShader("Shader Forge/main_opaque", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("Koikano/main_clothes_opaque", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("xukmi/MainOpaquePlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("xukmi/MainOpaquePlusTess", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("Shader Forge/main_opaque2", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AlphaMaskuv", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("Shader Forge/main_opaque_low", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("AnotherRamp", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("AlphaMaskuv", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float")
		}),
		new MaterialShader("Shader Forge/main_skin", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMapDetail", "Texture"),
			new MaterialShaderItem("NormalMask", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("alpha_a", "Float"),
			new MaterialShaderItem("alpha_b", "Float"),
			new MaterialShaderItem("DetailNormalMapScale", "Float"),
			new MaterialShaderItem("linetexon", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("nip", "Float"),
			new MaterialShaderItem("nipsize", "Float"),
			new MaterialShaderItem("nip_specular", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float"),
			new MaterialShaderItem("tex1mask", "Float")
		}),
		new MaterialShader("Koikano/main_skin", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMapDetail", "Texture"),
			new MaterialShaderItem("NormalMask", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("alpha_a", "Float"),
			new MaterialShaderItem("alpha_b", "Float"),
			new MaterialShaderItem("DetailNormalMapScale", "Float"),
			new MaterialShaderItem("linetexon", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("nip", "Float"),
			new MaterialShaderItem("nipsize", "Float"),
			new MaterialShaderItem("nip_specular", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float"),
			new MaterialShaderItem("tex1mask", "Float")
		}),
		new MaterialShader("xukmi/SkinPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMapDetail", "Texture"),
			new MaterialShaderItem("NormalMask", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("alpha_a", "Float"),
			new MaterialShaderItem("alpha_b", "Float"),
			new MaterialShaderItem("DetailNormalMapScale", "Float"),
			new MaterialShaderItem("linetexon", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("nip", "Float"),
			new MaterialShaderItem("nipsize", "Float"),
			new MaterialShaderItem("nip_specular", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float"),
			new MaterialShaderItem("tex1mask", "Float")
		}),
		new MaterialShader("xukmi/SkinPlusTess", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("AlphaMask", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("liquidmask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMapDetail", "Texture"),
			new MaterialShaderItem("NormalMask", "Texture"),
			new MaterialShaderItem("Texture2", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("LiquidTiling", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpecularColor", "Color"),
			new MaterialShaderItem("alpha_a", "Float"),
			new MaterialShaderItem("alpha_b", "Float"),
			new MaterialShaderItem("DetailNormalMapScale", "Float"),
			new MaterialShaderItem("linetexon", "Float"),
			new MaterialShaderItem("liquidbbot", "Float"),
			new MaterialShaderItem("liquidbtop", "Float"),
			new MaterialShaderItem("liquidface", "Float"),
			new MaterialShaderItem("liquidfbot", "Float"),
			new MaterialShaderItem("liquidftop", "Float"),
			new MaterialShaderItem("nip", "Float"),
			new MaterialShaderItem("nipsize", "Float"),
			new MaterialShaderItem("nip_specular", "Float"),
			new MaterialShaderItem("notusetexspecular", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("SpecularPower", "Float"),
			new MaterialShaderItem("SpecularPowerNail", "Float"),
			new MaterialShaderItem("tex1mask", "Float")
		}),
		new MaterialShader("Shader Forge/main_StandardMDK_studio", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("BumpMap", "Texture"),
			new MaterialShaderItem("EmissionMap", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("MetallicGlossMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("EmissionColor", "Color"),
			new MaterialShaderItem("BumpScale", "Float"),
			new MaterialShaderItem("EmissionPower", "Float"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("LightCancel", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("Specular", "Float")
		}),
		new MaterialShader("Shader Forge/main_texture", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("LineMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("ShadowColor", "Color"),
			new MaterialShaderItem("SpeclarHeight", "Float"),
			new MaterialShaderItem("ShadowExtend", "Float"),
			new MaterialShaderItem("ShadowExtendAnother", "Float"),
			new MaterialShaderItem("AnotherRampFull", "Float"),
			new MaterialShaderItem("DetailBLineG", "Float"),
			new MaterialShaderItem("DetailRLineR", "Float")
		}),
		new MaterialShader("Shader Forge/main_texture_studio", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Patternuv1", "Color"),
			new MaterialShaderItem("Cutoff", "Float"),
			new MaterialShaderItem("CutoutClip", "Float"),
			new MaterialShaderItem("patternclamp1", "Float"),
			new MaterialShaderItem("patternrotator1", "Float")
		}),
		new MaterialShader("Shader Forge/mnpb", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("WhiteOff", "Float")
		}),
		new MaterialShader("Shader Forge/toon_eye_lod0", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("expression", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("shadowcolor", "Color"),
			new MaterialShaderItem("isHighLight", "Float"),
			new MaterialShaderItem("exppower", "Float"),
			new MaterialShaderItem("rotation", "Float")
		}),
        new MaterialShader("Koikano/main_eye", new List<MaterialShaderItem>
        {
            new MaterialShaderItem("expression", "Texture"),
            new MaterialShaderItem("MainTex", "Texture"),
            new MaterialShaderItem("overtex1", "Texture"),
            new MaterialShaderItem("overtex2", "Texture"),
            new MaterialShaderItem("overcolor1", "Color"),
            new MaterialShaderItem("overcolor2", "Color"),
            new MaterialShaderItem("shadowcolor", "Color"),
            new MaterialShaderItem("isHighLight", "Float"),
            new MaterialShaderItem("exppower", "Float"),
            new MaterialShaderItem("rotation", "Float")
        }),
        new MaterialShader("xukmi/EyePlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("expression", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("shadowcolor", "Color"),
			new MaterialShaderItem("isHighLight", "Float"),
			new MaterialShaderItem("exppower", "Float"),
			new MaterialShaderItem("rotation", "Float")
		}),
		new MaterialShader("Shader Forge/toon_eyew_lod0", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("shadowcolor", "Color")
		}),
		new MaterialShader("Koikano/main_eyew", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("shadowcolor", "Color")
		}),
		new MaterialShader("xukmi/EyeWPlus", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("shadowcolor", "Color")
		}),
		new MaterialShader("Shader Forge/toon_nose_lod0", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color")
		}),
		new MaterialShader("Koikano/main_nose", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color")
		}),
		new MaterialShader("Shader Forge/toon_glasses_lod0", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("GlassRamp", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("ColorInverse", "Float"),
			new MaterialShaderItem("ColorSort", "Float"),
			new MaterialShaderItem("RimPower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("Koikano/main_clothes_item_glasses", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("GlassRamp", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("ColorInverse", "Float"),
			new MaterialShaderItem("ColorSort", "Float"),
			new MaterialShaderItem("RimPower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("Shader Forge/toon_textureanimation", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("TileAnimation", "Color"),
			new MaterialShaderItem("SizeSpeed", "Float"),
			new MaterialShaderItem("SizeWidth", "Float"),
			new MaterialShaderItem("AngleSpeed", "Float"),
			new MaterialShaderItem("yurayura", "Float")
		}),
		new MaterialShader("Koikano/sub_texture_animation", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("TileAnimation", "Color"),
			new MaterialShaderItem("SizeSpeed", "Float"),
			new MaterialShaderItem("SizeWidth", "Float"),
			new MaterialShaderItem("AngleSpeed", "Float"),
			new MaterialShaderItem("yurayura", "Float")
		}),
		new MaterialShader("Shader Forge/main_color", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("Color", "Color")
		}),
		new MaterialShader("Koikano/main_color", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("Color", "Color")
		}),
		new MaterialShader("IBL_Shader", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMap2", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("OutlineColor", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("rimcolor", "Color"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("Metallic", "Float"),
			new MaterialShaderItem("NormalScale", "Float"),
			new MaterialShaderItem("NormalScale2", "Float"),
			new MaterialShaderItem("Occlusion", "Float"),
			new MaterialShaderItem("Outline", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("IBL_Shader_alpha", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMap2", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("rimcolor", "Color"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("Metallic", "Float"),
			new MaterialShaderItem("NormalScale", "Float"),
			new MaterialShaderItem("NormalScale2", "Float"),
			new MaterialShaderItem("Occlusion", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("IBL_Shader_cutoff", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMap2", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("rimcolor", "Color"),
			new MaterialShaderItem("Cutoff", "Float"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("Metallic", "Float"),
			new MaterialShaderItem("NormalScale", "Float"),
			new MaterialShaderItem("NormalScale2", "Float"),
			new MaterialShaderItem("Occlusion", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("IBL_Shader_specular", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("GlossMap", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("NormalMap", "Texture"),
			new MaterialShaderItem("NormalMap2", "Texture"),
			new MaterialShaderItem("overtex1", "Texture"),
			new MaterialShaderItem("overtex2", "Texture"),
			new MaterialShaderItem("overtex3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("OutlineColor", "Color"),
			new MaterialShaderItem("overcolor1", "Color"),
			new MaterialShaderItem("overcolor2", "Color"),
			new MaterialShaderItem("overcolor3", "Color"),
			new MaterialShaderItem("rimcolor", "Color"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("Metallic", "Float"),
			new MaterialShaderItem("NormalScale", "Float"),
			new MaterialShaderItem("NormalScale2", "Float"),
			new MaterialShaderItem("Occlusion", "Float"),
			new MaterialShaderItem("Outline", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("rimpower", "Float"),
			new MaterialShaderItem("rimV", "Float")
		}),
		new MaterialShader("Standard", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("BumpMap", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("DetailAlbedoMap", "Texture"),
			new MaterialShaderItem("DetailMask", "Texture"),
			new MaterialShaderItem("DetailNormalMap", "Texture"),
			new MaterialShaderItem("EmissionMap", "Texture"),
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("MetallicGlossMap", "Texture"),
			new MaterialShaderItem("OcclusionMap", "Texture"),
			new MaterialShaderItem("ParallaxMap", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("EmissionColor", "Color"),
			new MaterialShaderItem("BumpScale", "Float"),
			new MaterialShaderItem("Cutoff", "Float"),
			new MaterialShaderItem("DetailNormalMapScale", "Float"),
			new MaterialShaderItem("DstBlend", "Float"),
			new MaterialShaderItem("Glossiness", "Float"),
			new MaterialShaderItem("Metallic", "Float"),
			new MaterialShaderItem("Parallax", "Float"),
			new MaterialShaderItem("SrcBlend", "Float"),
			new MaterialShaderItem("ZWrite", "Float")
		}),
		new MaterialShader("Shader Forge/create_body", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("Texture4", "Texture"),
			new MaterialShaderItem("Texture6", "Texture"),
			new MaterialShaderItem("paintmask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("Color5", "Color"),
			new MaterialShaderItem("Color6", "Color"),
			new MaterialShaderItem("paint1", "Color"),
			new MaterialShaderItem("paint2", "Color")
		}),
		new MaterialShader("Koikano/create_skinbody", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("Texture4", "Texture"),
			new MaterialShaderItem("Texture6", "Texture"),
			new MaterialShaderItem("paintmask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("Color5", "Color"),
			new MaterialShaderItem("Color6", "Color"),
			new MaterialShaderItem("paint1", "Color"),
			new MaterialShaderItem("paint2", "Color")
		}),
		new MaterialShader("Shader Forge/create_head", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("Texture4", "Texture"),
			new MaterialShaderItem("Texture5", "Texture"),
			new MaterialShaderItem("Texture6", "Texture"),
			new MaterialShaderItem("Texture7", "Texture"),
			new MaterialShaderItem("paintmask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("Color5", "Color"),
			new MaterialShaderItem("Color6", "Color"),
			new MaterialShaderItem("Color7", "Color"),
			new MaterialShaderItem("paint1", "Color"),
			new MaterialShaderItem("paint2", "Color"),
			new MaterialShaderItem("hokuro", "Color"),
			new MaterialShaderItem("tex4uv", "Color"),
			new MaterialShaderItem("tex5uv", "Color")
		}),
		new MaterialShader("Koikano/create_skinface", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Texture3", "Texture"),
			new MaterialShaderItem("Texture4", "Texture"),
			new MaterialShaderItem("Texture5", "Texture"),
			new MaterialShaderItem("Texture6", "Texture"),
			new MaterialShaderItem("Texture7", "Texture"),
			new MaterialShaderItem("paintmask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color4", "Color"),
			new MaterialShaderItem("Color5", "Color"),
			new MaterialShaderItem("Color6", "Color"),
			new MaterialShaderItem("Color7", "Color"),
			new MaterialShaderItem("paint1", "Color"),
			new MaterialShaderItem("paint2", "Color"),
			new MaterialShaderItem("hokuro", "Color"),
			new MaterialShaderItem("tex4uv", "Color"),
			new MaterialShaderItem("tex5uv", "Color")
		}),
		new MaterialShader("Shader Forge/create_eye", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("grad", "Color"),
			new MaterialShaderItem("Blend", "Float"),
			new MaterialShaderItem("Cutoff", "Float")
		}),
		new MaterialShader("Koikano/create_eye", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("grad", "Color"),
			new MaterialShaderItem("Blend", "Float"),
			new MaterialShaderItem("Cutoff", "Float")
		}),
		new MaterialShader("Shader Forge/create_eyewhite", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color")
		}),
		new MaterialShader("Koikano/create_eyew", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color2", "Color")
		}),
		new MaterialShader("Shader Forge/create_topN", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color1_2", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color2_2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color3_2", "Color"),
			new MaterialShaderItem("PatternScale1u", "Float"),
			new MaterialShaderItem("PatternScale1v", "Float"),
			new MaterialShaderItem("PatternScale2u", "Float"),
			new MaterialShaderItem("PatternScale2v", "Float"),
			new MaterialShaderItem("PatternScale3u", "Float"),
			new MaterialShaderItem("PatternScale3v", "Float"),
			new MaterialShaderItem("Cutoff", "Float")
		}),
		new MaterialShader("Koikano/create_topN", new List<MaterialShaderItem>
		{
			new MaterialShaderItem("MainTex", "Texture"),
			new MaterialShaderItem("ColorMask", "Texture"),
			new MaterialShaderItem("PatternMask1", "Texture"),
			new MaterialShaderItem("PatternMask2", "Texture"),
			new MaterialShaderItem("PatternMask3", "Texture"),
			new MaterialShaderItem("Color", "Color"),
			new MaterialShaderItem("Color1_2", "Color"),
			new MaterialShaderItem("Color2", "Color"),
			new MaterialShaderItem("Color2_2", "Color"),
			new MaterialShaderItem("Color3", "Color"),
			new MaterialShaderItem("Color3_2", "Color"),
			new MaterialShaderItem("PatternScale1u", "Float"),
			new MaterialShaderItem("PatternScale1v", "Float"),
			new MaterialShaderItem("PatternScale2u", "Float"),
			new MaterialShaderItem("PatternScale2v", "Float"),
			new MaterialShaderItem("PatternScale3u", "Float"),
			new MaterialShaderItem("PatternScale3v", "Float"),
			new MaterialShaderItem("Cutoff", "Float")
		})
	};
}
